### ISSUE TITLE
Logging in to your Linux computer using SSH and MFA: Spelling Error

### ISSUE THREAD

**Issue by austinsonger** [TheJumpCloud/support#126]
[Using Multi-factor Authentication with Your JumpCloud User Account](https://jumpcloud.desk.com/customer/portal/articles/2975258-using-multi-factor-authentication-with-your-jumpcloud-user-account-#Connect%20to%20wifi%20or%20VPN)
- Logging in to your Linux computer using SSH and MFA
   - To log in to your Linux system using SSH and MFA: 

ERROR
> Open your terminal, then run the ssh command with username@ipaddress as the argument. For example, `$ ssj auser@192.168.1.1`

Should be  `$ ssh auser@192.168.1.1`

**Comment by scottd3v** [comment]
Thank you! Great catch. This has been updated.
