### ISSUE TITLE
jc_install_jcagent_and_service_account script missing

### ISSUE THREAD

**Issue by olly6559** [TheJumpCloud/support#127]
The link for the script is missing in the guide below:
https://github.com/TheJumpCloud/support/blob/master/zero-touch/Jamf%20Pro/policies/Zero-Touch%20Step%201%20-%20JumpCloud%20Agent%20Install.md

**Comment by scottd3v** [comment]
This has been resolved. If you're looking to manage FileVault users using a zero-touch workflow see the new [pre-stage enrollment user workflow](https://github.com/TheJumpCloud/support/tree/master/zero-touch/prestage_user_enrollment)
