### ISSUE TITLE
InstallWindowsAgent.ps1 Key Parameter

### ISSUE THREAD

**Issue by ShaunInIdaho** [TheJumpCloud/support#145]
The way InstallWindowsAgent.ps1 is currently written it requires a user to edit the script prior to use.  This is not necessary and keeps the script from being used for unattended installations.

Replace `$JumpCloudConnectKey = '' ` with this to enable the script to take the key as a parameter:

> Param (
> [Parameter (Mandatory = $true)]
> [string] $JumpCloudConnectKey
> )

**Comment by scottd3v** [comment]
Great feedback! This has been resolved in [the last commit](https://github.com/TheJumpCloud/support/commit/382b4b112cde70f4827667b7eabd12ec8ac4f19b).
