### ISSUE TITLE
Update-JCUsersFromCSV silently fails

### ISSUE THREAD

**Issue by zaro0508** [TheJumpCloud/support#155]
"Update-JCUsersFromCSV" will not work when certain fields are in the csv file and the command doesn't throw an error so I didn't notice that it didn't actually update.  Anyways the following (and possibly other) fields, when set in the csv file, will cause that command to silently fail.  I say possibly others because I haven't tried them all.  

- account_locked
- enable_managed_uid
- enable_user_portal_multifactor
- ldap_binding_user
- password_never_expires
- passwordless_sudo
- sudo

 Those are fields that I would legitimately like to update.

**Comment by scottd3v** [comment]
Thanks for the feedback @zaro0508 . While we work to get this updated the command Set-JCUser can take input from a CSV and can be used in the short term to resolve this.

**Comment by zaro0508** [comment]
@scottd3v  I don't see any options to read from a CSV file using the [Set-JCUser command](https://github.com/TheJumpCloud/support/wiki/Set-JCUser), or am I missing something?
