### ISSUE TITLE
Non-Terminating Error in Connect-JCOnline

### ISSUE THREAD

**Issue by rybai** [TheJumpCloud/support#16]
https://github.com/TheJumpCloud/support/blob/b2b5c29a3edc54d61a6dd74b1a33ea82e2d2a2b0/PowerShell/JumpCloud.psm1#L63

In the try/catch block it is using `Write-Host` to output a failed connection/authentication. If `Write-Error` was used, we can catch this in controller scripts to stop processing if the initial handshake with JumpCloud fails. I think this fits PowerShell best practices as well.

**Comment by scottd3v** [comment]
Fixed in 1.4 release https://git.io/jc-pwsh-releasenotes
