### ISSUE TITLE
Error running jumpcloud test script

### ISSUE THREAD

**Issue by hongkongkiwi** [TheJumpCloud/support#17]
When running the JumpCloud test script I get:
`line 195: continue: only meaningful in a `for', `while', or `until' loop`

This happens right after I enter the organisational ID in the credentials setup.

**Comment by scottd3v** [comment]
Hey! Looking at line 195:
```
   It "Ensures the warning message is displayed by default, Deletes a single JumpCloud command result declaring -CommandResultIT" {
        $SingleCommandResult = Get-JCCommandResult | Select-Object -Last 1
        $DeletedResult = Remove-JCCommandResult -CommandResultID $SingleCommandResult._id
        $DeletedResult._id.count | Should -Be 1
    }
```
This test is ensuring that there is a promp shown when deleing a command.

Before you can run the tests you must install Pester and also set up a test org that meets all the testing criteria.

After this org is set up you then populate the variables in the top of the .tests.ps1 file.

Have you completed these steps?

**Comment by sondreengebraten** [comment]
Hi!

This issue happens if the password contains a special character at the end like !

**Comment by flybyray** [comment]
@scottd3v the answesers are just non-sense

The script mentioned is https://github.com/TheJumpCloud/support/blob/master/scripts/jumpcloud_test_utility.sh which is linked from various knowledge base articles.
The error is bash context error. The exact line is now here

https://github.com/TheJumpCloud/support/blob/master/scripts/jumpcloud_test_utility.sh#L215

You can run it with `bash -x ...` to have a more clear understanding what happens here:

```text
+ cat
###########################
####    Main Menu     #####
###########################

1. Enter LDAP account variables
2. Set LDAP port 389 (STARTTLS)
3. Set LDAP port 636 (SSL)
4. LDAP Search Menu
5. Display Common LDAP settings
6. API access
9. Help
0. Exit
+ read_main_menu
+ echo -ne '\nSelect an option: '

Select an option: + read option
1
+ case $option in
+ read_account
+ read_user
+ echo -n 'Enter LDAP Binding User account name: '
Enter LDAP Binding User account name: + read user
svc-openshift
+ '[' -z svc-openshift ']'
+ read_pass
+ echo -n 'Enter password: '
Enter password: + read -s pass
+ echo

+ '[' -z typed_password ']'
+ read_oid
+ echo -n 'Enter the organization ID: '
Enter the organization ID: + read oid
typed_orgid
+ '[' -z typed_orgid ']'
+ continue
./jumpcloud_test_utility.sh: line 215: continue: only meaningful in a `for', `while', or `until' loop
+ read_pass
+ echo -n 'Enter password: '
```

["Thanks for looking so deep into this one."](https://github.com/TheJumpCloud/support/issues/39#issuecomment-437705120)
