### ISSUE TITLE
./RADIUS_IP_Update.sh: 73: ./RADIUS_IP_Update.sh: Syntax error: "(" unexpected (expecting "fi")

### ISSUE THREAD

**Issue by Dreamurrrr** [TheJumpCloud/support#184]
./RADIUS_IP_Update.sh: 73: ./RADIUS_IP_Update.sh: Syntax error: "(" unexpected (expecting "fi")

**Comment by wilsonsyl** [comment]
Yes, I also receive this error message.

**Comment by SysAdminSeth** [comment]
I also experienced this issue.

I fixed the bug and it is currently waiting on a pull request: https://github.com/TheJumpCloud/support/pull/290
