### ISSUE TITLE
Error when running renaming script

### ISSUE THREAD

**Issue by graemehwalker** [TheJumpCloud/support#196]
Getting an error when running the renaming script (using separate administrator account).

- Popup stating "Terminal" requesting permission to access computer.
- Click "OK" to allow.
- Script runs but confuses the users details.

- Example: When trying to rename Josh to JAF, it attempts to rename the user folder to /Users/Josh/Jaf (see attached images).

Any assistance would be greatly appreciated.

<img width="419" alt="Screenshot 2020-01-14 at 09 41 57" src="https://user-images.githubusercontent.com/59867708/72333789-4d78d880-36b4-11ea-9259-3dd402b0a5d2.png">

<img width="877" alt="Screenshot 2020-01-14 at 09 42 21" src="https://user-images.githubusercontent.com/59867708/72333800-52d62300-36b4-11ea-8cf9-e0695ad39749.png">

**Comment by graemehwalker** [comment]
Found this article: http://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/
This may be the solution.

**Comment by jworkmanjc** [comment]
@graemehwalker is it possible that your user "Josh" has a different home directory name? The rename script expects that the username and the home directory are titled the exact same.
