### ISSUE TITLE
Username is required to be case sensitive

### ISSUE THREAD

**Issue by Rocketman-Chris** [TheJumpCloud/support#200]
This script will fail if the local username does not match the exact case of the username in JumpCloud. However, it appears that the local username matching the case of the username in JumpCloud is not required. The "IF" statement is exiting with an error when the script would otherwise run properly.

**Comment by jworkmanjc** [comment]
@rocketman-tech to which script in this repository does this issue refer to? I can take a look at this.

**Comment by bi89** [comment]
I use "Add-JCSystemUser", it is also case sensitive.

`Add-JCSystemUser -Username $username -Administrator $False`
