### ISSUE TITLE
macOS user rename script fails if username being changed is a substring of the logged in user

### ISSUE THREAD

**Issue by hpanderson** [TheJumpCloud/support#208]
I ran into an unusual error with the macOS rename script. I'm trying to rename the user **hank**, and I'm logged in to another account of a coworker named Jonathan K., with a username **jonathank**. The rename script claims **hank** is logged in, then fails to log that user out with an error `unrecognized domain-target specifier`.

Turns out the `loginCheck` command always returns true as it is finding processes belonging to **jonathank**. Adding the `-w` switch to grep solves the issue.

**Comment by jworkmanjc** [comment]
Thanks @hpanderson, this is fixed in [PR 209](https://github.com/TheJumpCloud/support/pull/209) - marking this as closed for now.
