### ISSUE TITLE
additional pre-built commands for MacOS

### ISSUE THREAD

**Issue by jefimm** [TheJumpCloud/support#232]
Additional MacOS commands to install https://www.tunnelblick.net/ and homebrew (https://brew.sh/) would be greatly appreciated  in support/PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/

**Comment by romancieslik-tame** [comment]
@jefimm How did you solve this without a pre-built command?

**Comment by jefimm** [comment]
there is an install template now in the jumpcloud ui - you can customize it
