### ISSUE TITLE
The code provided in the website isn't work to update the radius setting

### ISSUE THREAD

**Issue by ghost** [TheJumpCloud/support#235]
The below code is not work. It will return error "shared secret must not empty".
curl \
  -X 'PUT' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -H "x-api-key: YOUR_API_KEY" \
  -d '{"networkSourceIp":"YOUR.NEW.IP.ADDR"}' \
  "https://console.jumpcloud.com/api/radiusservers/:id""

Finally I wrote the below code and tested, it works.
*Please change the below before you use:
:your_api_key, :your_radius_name, :your_radius_shared_secret, :radius_id, :mfa_status (Enabled/Disabled), :userLockoutAction (MANTAIN/REMOVE), :PasswordExpirationAction (MANTAIN/REMOVE)

curl
-X 'PUT'
-H 'Content-Type: application/json'
-H 'Accept: application/json'
-H "x-api-key: :your_api_key"
-d '{"name" : ":your_radius_name", "sharedSecret" : ":your_radius_shared_secret", "networkSourceIp":"'"$(curl -q http://ipecho.net/plain)"'","mfa":":mfa_status","userLockoutAction":":userLockoutAction","userPasswordExpirationAction":":PasswordExpirationAction"}' \
  "https://console.jumpcloud.com/api/radiusservers/:radius_id"

**Comment by Dreamurrrr** [comment]
This is similar to #184. JumpCloud come on, you guys can do better.

**Comment by jworkmanjc** [comment]
@wilsonsyl Thanks for noting this, looks like that support documentation is out of date, I'm glad you figured out that correct syntax. I'm going to work to get that article updated with correct syntax.
