### ISSUE TITLE
Dialing LDAP: address 127.0.0.1:389 how to change via LDAPS

### ISSUE THREAD

**Issue by Emilyen777** [TheJumpCloud/support#322]
Hi Dear support,

I will appreciate any support. I have configured AD Import and AD Sync agents as here 
https://support.jumpcloud.com/support/s/article/Upcoming-Updates-to-the-AD-Import-and-AD-Sync-Agents-for-LDAPS#ImportChanges

but in the logs, I see that the agent still tries to connect to 127.0.0.1. 

{"level":"info","msg":"Dialing LDAP: address 127.0.0.1:389, bindUser RH\\jump.sync","time":"2021-12-01T01:49:27.1847397+11:00"}
{"date":"'Tue Apr 21 17:54:36 UTC 2020'","goversion":"go1.11.5","level":"info","msg":"starting","name":"jumpcloud-adbridge-agent","revision":"7b1b0f6324fc3536af98ed9b82350896c6f53a90","time":"2021-12-01T01:49:27.2142439+11:00","version":"v2.26.0"}
{"level":"info","msg":"opening new connection","target":"adbridge-kickstart.jumpcloud.com","time":"2021-12-01T01:49:27.2142439+11:00"}
{"addrs":["adbridge.jumpcloud.com:443"],"level":"info","msg":"dialing","target":"adbridge.jumpcloud.com","time":"2021-12-01T01:49:27.2152371+11:00","tls":{"ca":"present","certs":"present","server_name":"adbridge.jumpcloud.com"}}
{"level":"info","msg":"opening new connection","target":"adbridge.jumpcloud.com","time":"2021-12-01T01:49:27.2152371+11:00"}

I have opened the case in JumpCLoud support but support could not give me any solution.

Thanks

**Comment by jworkmanjc** [comment]
Hi @Emilyen777, 

JumpCloud support is your best bet here, this repository does not contain any code related to AD Import/ Sync. That KB article notes that you need to change your hostname to it's FQND - you must restart the AD Import agent service for those changes to take effect. Please reach out to support for additional help using the AD Import/ Sync products.
