### ISSUE TITLE
JC_RENAME: Error: sh requires two parameters

### ISSUE THREAD

**Issue by GaryQuay** [TheJumpCloud/support#339]
getting this error when running 
2022-01-25--11:31:37 JC_RENAME: ## Rename Script Begin ##
kTCCServiceSystemPolicyAllFiles|com.sophos.endpoint.scanextension|0|2|4|1|��||0|UNUSED||0|163997
0228
kTCCServiceSystemPolicyAllFiles|com.sophos.macendpoint.SophosServiceManager|0|2|4|1|��||0|UNUSED
||0|1639970229
kTCCServiceScreenCapture|com.google.Chrome|0|2|4|1|��||0|UNUSED||0|1639987980
kTCCServiceSystemPolicyAllFiles|/System/Library/PrivateFrameworks/AppStoreDaemon.framework/Suppor
t/appstored|1|0|5|1|��|||UNUSED||0|1640037584
kTCCServiceScreenCapture|com.tinyspeck.slackmacgap|0|2|4|1|��||0|UNUSED||4|1640074467
kTCCServiceDeveloperTool|com.apple.Terminal|0|0|4|1|||0|UNUSED||0|1640209703
kTCCServiceSystemPolicyAllFiles|com.apple.Terminal|0|0|5|1|��|||UNUSED||0|1640212881
kTCCServiceAccessibility|com.google.chromeremotedesktop.me2me-host|0|2|4|1|��||0|UNUSED||0|16402
19841
kTCCServiceScreenCapture|com.google.chromeremotedesktop.me2me-host|0|2|4|1|��||0|UNUSED||0|16402
19847
kTCCServiceAccessibility|com.google.chrome.remote_desktop.remote-assistance-host-v2|0|2|4|1|��||
0|UNUSED||0|1640825195
kTCCServiceAccessibility|com.apple.ScriptEditor2|0|0|4|1|��||0|UNUSED||0|1640825195
kTCCServiceSystemPolicyAllFiles|com.jamf.opensource.pppcutility|0|2|4|1|��||0|UNUSED||0|16408348
26
kTCCServiceAccessibility|com.google.drivefs|0|0|4|1|��||0|UNUSED||0|1640841399
kTCCServiceSystemPolicyAllFiles|com.microsoft.VSCode|0|0|5|1|��|||UNUSED||0|1641265811
kTCCServiceSystemPolicyAllFiles|/Library/Google/GoogleSoftwareUpdate/GoogleSoftwareUpdate.bundle/
Contents/Helpers/GoogleSoftwareUpdateDaemon|1|0|5|1|��|||UNUSED||0|1641305200
kTCCServiceScreenCapture|com.google.chrome.remote_desktop.remote-assistance-host-v2|0|0|4|1|��||
0|UNUSED||0|1641356620
kTCCServiceSystemPolicyAllFiles|us.zoom.xos|0|0|5|1|��|||UNUSED||0|1641545609
kTCCServiceAccessibility|us.zoom.xos|0|0|4|1|��||0|UNUSED||0|1641545628
kTCCServiceSystemPolicyAllFiles|com.apple.dt.Xcode|0|0|5|1|��|||UNUSED||0|1641792556
kTCCServiceSystemPolicyAllFiles|com.xamarin.visualstudioformacinstaller|0|0|5|1|��|||UNUSED||0|1
641941812
kTCCServiceListenEvent|com.tinyspeck.slackmacgap|0|0|6|2|��|||UNUSED||12|1641952452
2022-01-25--11:31:37 JC_RENAME: Error: sh requires two parameters

**Comment by jworkmanjc** [comment]
Hi @GaryQuay,

Renaming users is tricky business, There's a note about this script both [here](https://github.com/TheJumpCloud/support/releases/tag/MacRenamev1.0.1) and on this [blog](https://jumpcloud.com/blog/renaming-an-existing-user-on-macos).

In this case it looks like you are missing the oldname, or newname parameter when running the script. Could you confirm you are running this correctly? In addition [Apple has a support page](https://support.apple.com/en-us/HT201548) if you wish to rename a user using their official workflow.

Best,
Joe
