### ISSUE TITLE
Get-JCSystemGroupMember limits results to 200

### ISSUE THREAD

**Issue by bhavekost** [TheJumpCloud/support#369]
**Describe the bug**
When running `Get-JCSystemGroupMember -groupname 'whatever'` the function only returns up to 200 values. 

**To Reproduce**
Run `Get-JCSystemGroupMember -groupname 'whatever` on a device group with >200 users and compare the output from the PowerShell function and the GUI.

**Expected behavior**
The results should match the GUI number of results, and not limit to 200.

****System Device (please complete the following information):****
 - OS: Windows 11
 - Version 10.0.22000 N/A Build 22000
 - PowerShell 7.2.2

**Comment by jworkmanjc** [comment]
@bhavekost, I saw your issue. I believe we have a fix for this in the works for planned release this week.

The way the PowerShell Module and SDKs paginate between pages of data currently assumes that we receive a page of results which is less than the current limit (generally 100 records per page), the function is done collecting all data from the organization. What we've found is that an organization can have null records to systems set in their system groups associations database. In that case the PowerShell Module will stop returning results once the it finds an association to a null system. In your case it looks like it's only returning 200 systems. 

We believe the better way to paginate is to first get the count of all records and generate the number of pages to query. This should solve for the issue you are experiencing and all valid data from device groups will be returned even if there's a null record on the associations database. Even if we encounter a record to a null (non-existant) associated system, the function should continue to paginate until we reach the calculated end of available pages.

I'll link this issue to the next release when it's made available.

**Comment by jworkmanjc** [comment]
@bhavekost, we released the 1.20.1 version of the powershell module this afternoon. Can you update and confirm that the `Get-JCSystemGroupMember -groupname 'whatever'` command returns the correct number of systems?

**Comment by jworkmanjc** [comment]
@bhavekost  I'm closing this, we believe this has been resolved but have not heard back

**Comment by bhavekost** [comment]
@jworkmanjc my apologies on the slowness.  
Yes it is fixed.  Much appreciated!
