### ISSUE TITLE
Cannot push install DMG file from commands because of License Agreement

### ISSUE THREAD

**Issue by husaini-alsaid** [TheJumpCloud/support#388]
Hi JumpCloud team,

I'm having an issue with installing the application on macOS via command push.

The name of the application is LinPhone and the link for the software is below:-
https://raw.githubusercontent.com/husaini-alsaid/SIP-Softphone/main/Linphone-4.4.1-mac.dmg

Currently, I'm testing to install LinPhone software on my MacBook.
I got the code from GitHub (https://github.com/TheJumpCloud/support/blob/master/PowerShell/JumpCloud%20Commands%20Gallery/Mac%20Commands/Application%20Installs/Mac%20-%20Generic%20DMG%20Installer.md)

However, If I installing manually it require to accept the License agreement to mount the DMG.

Please help me.

Thanks.

**Comment by jworkmanjc** [comment]
Hi @husaini-alsaid, that template file you are attempting to use will not handle license agreements. You'll need to either solve for the issue or consider packaging your software as a deployable .pkg file. I've had success with [Packages](http://s.sudre.free.fr/Software/Packages/about.html) in the past and find it to be a robust packaging solution.
