### ISSUE TITLE
Test utility presents error on Pop_OS!

### ISSUE THREAD

**Issue by ecapuano** [TheJumpCloud/support#39]
I get the following error when trying to set the variables through the script menus. 

```
###### LDAP Search Options ######"

1. List Users
2. List POSIX Groups
3. List Groups of Names
4. List all Objects
0. Main Menu

Select an option: 1

Account variables undefined, enter information and reselect

Enter LDAP Binding User account name: <redacted>
Enter password: 
Enter the organization ID: <redacted>
./jumpcloud_test_utility.sh: line 195: continue: only meaningful in a `for', `while', or `until' loop

```

**Comment by scottd3v** [comment]
Thanks for the note. At this time Pop_OS is not a supported distribution of Linux. Find a list of all supported versions [here](https://support.jumpcloud.com/customer/portal/articles/2390451#linux)

**Comment by ecapuano** [comment]
For the record, Pop_OS is just Ubuntu 18.04 under an Elementary-type skin... I've opened multiple tickets about JumpCloud having issues on vanilla Ubuntu, too, but that's a separate issue. Thanks for looking so deep into this one.
