### ISSUE TITLE
support

### ISSUE THREAD

**Issue by ramindadoo54** [TheJumpCloud/support#393]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Links**
Links to file or script with regards to the issue.

**Screenshots**

****System Device (please complete the following information):****

**Additional context**
For feature requests, go to: https://support.jumpcloud.com/support/s/article/to-submit-a-jumpcloud-feature-request2

**Comment by jworkmanjc** [comment]
closing, no content
