### ISSUE TITLE
Enhance SetJCSystem to add/change description field

### ISSUE THREAD

**Issue by juergen-kc** [TheJumpCloud/support#432]
**Describe the bug**
Hello, I'd like to be able to add/change the description of a system by using:
https://github.com/TheJumpCloud/support/blob/master/PowerShell/JumpCloud%20Module/Docs/Set-JCSystem.md

**To Reproduce**
-/-

**Expected behavior**
Add a parameter "-description" followed by a string
Currently as 'get' only.

**Links**
[Links to file or script with regards to the issue.](https://docs.jumpcloud.com/api/1.0/index.html#tag/Systems/operation/systems_put)

**Screenshots**

****System Device (please complete the following information):****

**Additional context**
For feature requests, go to: https://support.jumpcloud.com/support/s/article/to-submit-a-jumpcloud-feature-request2

**Comment by jworkmanjc** [comment]
Closing, resolved in #440
