### ISSUE TITLE
'Generate-UserCerts.ps1' does not account for new devices for previously RADIUS-bounded Users

### ISSUE THREAD

**Issue by sonny-mei** [TheJumpCloud/support#561]
The 'Generate-UserCerts.ps1' checks if users are already included in the user.json. However, in cases where new devices are binded to the user, the user.json file does not properly add these new devices.
![image](https://github.com/TheJumpCloud/support/assets/153926775/d8bda82e-731e-49c6-b4e1-5c443cbfbeff)

Thus, within 'Distribute-UserCerts.ps1', the user certs will not be pushed to these new devices as it relies on user.json which will not contain the new devices. 
![image](https://github.com/TheJumpCloud/support/assets/153926775/d0ed4646-87cd-4d39-8237-ba9ec47fbe1e)

Is there a way to resolve this issue?

**Comment by sonny-mei** [comment]
This issue is for 'Passwordless User Certificate Radius Certificate Generation v1.0.5'

https://github.com/TheJumpCloud/support/releases/tag/PasswordlessRadiusConfig_v1.0.5

**Comment by sonny-mei** [comment]
Also, I don't the script will **removed** users that have been unlinked from the JC RADIUS User Group.

**Comment by jworkmanjc** [comment]
Hello @sonny-mei, yes this is a limitation of the current release. I've been working on a version of the tool that accounts for this and addresses the other issue you've raised in this repository. 

If you are interested you can check out this branch https://github.com/TheJumpCloud/support/tree/Radius_2.0.0

In this branch, the way we query user group membership has changed significantly. Membership of the radius group is updated when you run the tool and every hour afterwards. By caching data about your JumpCloud org, we can reduce the number of API calls required to distribute Radius certificates. 

There still remains work before the 2.0.0 version of the tool is officially released. I'll go ahead and patch your other issue raised in the 1.0.0 branch. Let me know if you'd like to chat about the usage of the tool at all?

**Comment by sonny-mei** [comment]
Hello Joe,

Thank you for the reply. I believe I should be fine for now, but thank you for offering a time to chat. Do you happen to know the anticipated release date for version 2.0.0? 

Best Regards,
Sonny Mei

**Comment by jworkmanjc** [comment]
Not sure on the 2.0.0 work, I should also mention that the 1.0.7 version of the Radius deploy example scripts is published https://github.com/TheJumpCloud/support/releases/tag/PasswordlessRadiusConfig_v1.0.7  — which I do believe resolves the issue noted #560 and is two patch versions along further than the 1.0.5 version you've noted in these two issues.

**Comment by jworkmanjc** [comment]
Ah good catch, I'll get that updated!
