### ISSUE TITLE
Set-JCUser cannot be used safely with concurrent calls

### ISSUE THREAD

**Issue by lsibilla** [TheJumpCloud/support#622]
**Describe the bug**
I'm trying to automate the addition of user attributes to match with the project's role structure of our organisation.

While doing a preliminary test, I created a custom attribute `TestAttribute1`, then concurrently remove `TestAttribute1` and create `TestAttribute2`.

Both commands ran successfully. Nevertheless, 2 concurrent commands only created the new attribute.

I can see the in the output of step 2.1 below that `TestAttribute1` got removed. Nevertheless, in the output of step 2.2, `TestAttribute1` was restored in addition of `TestAttribute2` being added.

**To Reproduce**
- Step 1:
```
Set-JCUser -Username 'SomeTestUser' -NumberOfCustomAttributes 1 -Attribute1_name 'TestAttribute1' -Attribute1_value 'TestValue1'
```
- Step 2:
```
Start-Job -ScriptBlock { Set-JCUser -Username 'SomeTestUser' -RemoveCustomAttribute 'TestAttribute1' }
Start-Job -ScriptBlock { Set-JCUser -Username 'SomeTestUser' -NumberOfCustomAttributes 1 -Attribute1_name 'TestAttribute2' -Attribute1_value 'TestValue2' }   
```

**Expected behavior**
I want to be able to send commands concurrently. Requests that don't collide should play nice with each other and provide a consistent result state.

If there is a risk of collision, the API call should fail.

**Links**
(None)

**Screenshots**
(None)

****System Device (please complete the following information):****
 - OS: MacOs
 - Version PowerShell module 2.15.0 running on PowerShell Core 7.4.6

**Additional context**
For feature requests, go to: https://support.jumpcloud.com/support/s/article/to-submit-a-jumpcloud-feature-request2

**Comment by jworkmanjc** [comment]
Hello @lsibilla, 

I believe I understand your issue, thanks for taking the time to detail the issue clearly. User attributes are not described in our API as a true PUT endpoint — meaning you have to post the whole attribute body when you "update" some user.

If you actually watch the web traffic each request to edit the attributes for a given user will actually post PUT the entire attribute body for the given user:

`#pseudoCode
# add the first attribute
$body = @{
    attributes = @{
         "TestAttribute1" = "TestValue1"
    }
} | ConvertTo-JSON -depth 99
invoke-webRequest -URI "console.jumpcluod.com/users/{someUserID} -Method PUT -Body $body
`
To add another attribute on this endpoint I need to pass in the whole attribute body
`#pseudoCode
# add another attribute
$body = @{
    attributes = @{
         "TestAttribute1" = "TestValue1"
         "TestAttribute2" = "TestValue2"
    }
} | ConvertTo-JSON -depth 99
invoke-webRequest -URI "console.jumpcluod.com/users/{someUserID} -Method PUT -Body $body
`

To remove an attribute on this endpoint I need to pass in the whole attribute body, minus the attribute I want to remove
`#pseudoCode
# add another attribute
$body = @{
    attributes = @{
         "TestAttribute2" = "TestValue2"
    }
} | ConvertTo-JSON -depth 99
invoke-webRequest -URI "console.jumpcluod.com/users/{someUserID} -Method PUT -Body $body
`

This specific property works in this manner and is not editable on the individual sub-property level. Concurrent calls to user attributes would be problematic. I don't see a way around this sadly. 

This function will "GET" the current attributes for users to effectively allow you to add attributes without having to know all the user's attributes up front. This is why your test scenario failed. If both 2.1 and 2.2 run at the same time, both cmdlet calls would have gotten the attribute Body that looks like:
`
@{
    attributes = @{
         "TestAttribute1" = "TestValue1"
    }
`
The first call would remove that attribute, the second (and the function that ran last) would post this structure to the body:
`@{
    attributes = @{
         "TestAttribute1" = "TestValue1"
         "TestAttribute2" = "TestValue2"
    }`
Resulting in what looks like the first attribute not being removed. 

I would not suggest running updates to some user's attributes in parallel. You could update separate users attributes in parallel however.

Best,
Joe

**Comment by lsibilla** [comment]
Hi @jworkmanjc 

Thank you for your feedback.

It may be a good idea to provide a `PATCH` HTTP method in the API.

In the meantime, I have introduced a global mutex in my script to workaround the issue.

**Comment by jworkmanjc** [comment]
Indeed, there are many of our endpoints which would benefit from a true `PATCH` method. I'm going to close this issue but please if you have a moment [submit a feature request](https://jumpcloud.com/support/request-features). It helps our product teams prioritize issues that are most pressing.
