### ISSUE TITLE
windows agent install script is not automated

### ISSUE THREAD

**Issue by zaro0508** [TheJumpCloud/support#85]
I wanted to use your script[1] to run an automated command line install of the jumpcloud agent however when I run it a dialog pops up that says..
 
```
The following applications are required before setup can continue: 
  MS Visual C++ 2013 Redistributable package (x86) (6.5 MB)
  MS Visual C++ 2013 Redistributable package (x64) (7.2 MB)

Download and install now?
```
https://imgur.com/a/HyNgZie

Is it possible to ignore the pop-up and just force accept those dependencies?   I'm running the script from an AWS windows 2019 server base image[2]

[1] https://github.com/TheJumpCloud/support/blob/master/scripts/windows/FixWindowsAgent.ps1
[2] Windows_Server-2019-English-Full-Base-2019.03.13 (ami-02d43577e47e684d9)

**Comment by scottd3v** [comment]
This has been resolved in the last commit.

https://github.com/TheJumpCloud/support/commit/382b4b112cde70f4827667b7eabd12ec8ac4f19b
